import React, { PureComponent } from 'react';
import styles from './PCs.css';

export default class Notes extends PureComponent {
  render() {    
    return (
      <div>
        <h1>PCs</h1>
        <div className={styles.pc}>
          <h4>Name</h4>
          <table>
            <thead>
              <tr>
                <th>DR</th>
                <th>STR</th>
                <th>AGI</th>
                <th>END</th>
                <th>Will</th>
                <th>CHA</th>
                <th>REA</th>
                <th>PER</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
              </tr>
            </tbody>
          </table>
        </div>

        <div className={styles.pc}>
          <h4>Name</h4>
          <table>
            <thead>
              <tr>
                <th>DR</th>
                <th>STR</th>
                <th>AGI</th>
                <th>END</th>
                <th>Will</th>
                <th>CHA</th>
                <th>REA</th>
                <th>PER</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
              </tr>
            </tbody>
          </table>
        </div>

        <div className={styles.pc}>
          <h4>Name</h4>
          <table>
            <thead>
              <tr>
                <th>DR</th>
                <th>STR</th>
                <th>AGI</th>
                <th>END</th>
                <th>Will</th>
                <th>CHA</th>
                <th>REA</th>
                <th>PER</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
              </tr>
            </tbody>
          </table>
        </div>

        <div className={styles.pc}>
          <h4>Name</h4>
          <table>
            <thead>
              <tr>
                <th>DR</th>
                <th>STR</th>
                <th>AGI</th>
                <th>END</th>
                <th>Will</th>
                <th>CHA</th>
                <th>REA</th>
                <th>PER</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
              </tr>
            </tbody>
          </table>
        </div>

        <div className={styles.pc}>
          <h4>Name</h4>
          <table>
            <thead>
              <tr>
                <th>DR</th>
                <th>STR</th>
                <th>AGI</th>
                <th>END</th>
                <th>Will</th>
                <th>CHA</th>
                <th>REA</th>
                <th>PER</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
              </tr>
            </tbody>
          </table>
        </div>

        <div className={styles.pc}>
          <h4>Name</h4>
          <table>
            <thead>
              <tr>
                <th>DR</th>
                <th>STR</th>
                <th>AGI</th>
                <th>END</th>
                <th>Will</th>
                <th>CHA</th>
                <th>REA</th>
                <th>PER</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
              </tr>
            </tbody>
          </table>
        </div>

      </div>
    );
  }
}